# Generated by Django 4.1.3 on 2022-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legnth', models.IntegerField()),
                ('width', models.IntegerField()),
                ('house_id', models.IntegerField(blank=True, max_length=1, null=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('product_type', models.CharField(max_length=10)),
                ('num_of_bedrooms', models.IntegerField(max_length=2)),
                ('num_of_bathrooms', models.IntegerField(max_length=2)),
                ('about', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='Product')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
