# Generated by Django 4.1.4 on 2022-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='house_id',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_bathrooms',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_bedrooms',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
