# Generated by Django 4.1.3 on 2022-12-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0004_product_house_id_alter_product_num_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legnth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
