# Generated by Django 4.1.3 on 2022-12-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0005_product_legnth_product_product_name_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
